cacheFolder: .yarn/cache

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  pixelcoda:
    npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "https://npm.pkg.github.com":
    # npmAuthToken set via yarn config set in CI
  "https://registry.npmjs.org":
    # npmAuthToken set via yarn config set in CI
